CREATE DATABASE QUESTAO8;

USE QUESTAO8;
CREATE TABLE ENDERECO (
ID INT PRIMARY KEY NOT NULL,
RUA VARCHAR(30),
CEP VARCHAR(8),
BAIRRO VARCHAR(100),
CIDADE VARCHAR(100),
UF_ESTADO VARCHAR(2),
COMPLEMENTO VARCHAR(255)
);

CREATE TABLE EDITORA (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR(100),
ID_ENDERECO INT NOT NULL,
FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)
);

CREATE TABLE AUTOR (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR(100),
ID_ENDERECO INT NOT NULL,
FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)
);

CREATE TABLE LIVRO (
ID INT PRIMARY KEY NOT NULL,
TITULO VARCHAR(100),
ID_EDITORA INT,
ID_AUTOR INT,
CATEGORIA VARCHAR(30),
FOREIGN KEY (ID_EDITORA) REFERENCES EDITORA (ID),
FOREIGN KEY (ID_AUTOR) REFERENCES AUTOR (ID)
);

CREATE TABLE LEITOR (
ID INT PRIMARY KEY NOT NULL,
NOME VARCHAR(100),
ID_ENDERECO INT NOT NULL,
FOREIGN KEY (ID_ENDERECO) REFERENCES ENDERECO (ID)
);

CREATE TABLE EMPRESTIMO (
ID INT PRIMARY KEY NOT NULL,
DATA_EMPRESTIMO DATE,
ID_LEITOR INT NOT NULL,
ID_LIVRO INT NOT NULL,
FOREIGN KEY (ID_LEITOR) REFERENCES LEITOR (ID),
FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO (ID)
);
